BEGIN TRANSACTION;
CREATE TABLE [TB_HABILIDADES] (
    [Id] int NOT NULL IDENTITY,
    [Nome] varchar(200) NOT NULL,
    [Dano] int NOT NULL,
    CONSTRAINT [PK_TB_HABILIDADES] PRIMARY KEY ([Id])
);

CREATE TABLE [TB_PERSONAGENS_HABILIDADES] (
    [PersonagemId] int NOT NULL,
    [HabilidadeId] int NOT NULL,
    [PersonagemHabilidadeHabilidadeId] int NULL,
    [PersonagemHabilidadePersonagemId] int NULL,
    CONSTRAINT [PK_TB_PERSONAGENS_HABILIDADES] PRIMARY KEY ([PersonagemId], [HabilidadeId]),
    CONSTRAINT [FK_TB_PERSONAGENS_HABILIDADES_TB_HABILIDADES_HabilidadeId] FOREIGN KEY ([HabilidadeId]) REFERENCES [TB_HABILIDADES] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_TB_PERSONAGENS_HABILIDADES_TB_PERSONAGENS_HABILIDADES_PersonagemHabilidadePersonagemId_PersonagemHabilidadeHabilidadeId] FOREIGN KEY ([PersonagemHabilidadePersonagemId], [PersonagemHabilidadeHabilidadeId]) REFERENCES [TB_PERSONAGENS_HABILIDADES] ([PersonagemId], [HabilidadeId]),
    CONSTRAINT [FK_TB_PERSONAGENS_HABILIDADES_TB_PERSONAGENS_PersonagemId] FOREIGN KEY ([PersonagemId]) REFERENCES [TB_PERSONAGENS] ([Id]) ON DELETE CASCADE
);

IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'Dano', N'Nome') AND [object_id] = OBJECT_ID(N'[TB_HABILIDADES]'))
    SET IDENTITY_INSERT [TB_HABILIDADES] ON;
INSERT INTO [TB_HABILIDADES] ([Id], [Dano], [Nome])
VALUES (1, 39, 'Adormecer'),
(2, 41, 'Congelar'),
(3, 37, 'Hipnotizar');
IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'Dano', N'Nome') AND [object_id] = OBJECT_ID(N'[TB_HABILIDADES]'))
    SET IDENTITY_INSERT [TB_HABILIDADES] OFF;

UPDATE [TB_USUARIOS] SET [PasswordHash] = 0x96E7E15C95768528C5903AD9023896CCB99FF15572BA20C3884256B7F81C77A8507B472ED020E96C9A64F0E89720545B23F71F41A28EE3A1138295D8C5DDA459, [PasswordSalt] = 0x4D1BE9E0D5B8C1D859E045560B7CC996BB6DA35AE8DF871FAA3D5F0C39D200435D540A34409A767924B2C66CA49DE60BBEA36489EF36180DC30D6C2F84C9BD6D594A59A5A23D8B0E2F52A357024E5F46320E0DF2F4256343FA51C85FD82ED35069C9A1D52616DAEB0DB53564E74905C1F590AB86B4B63448766DC3B98C5EAE94
WHERE [Id] = 1;
SELECT @@ROWCOUNT;


IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'HabilidadeId', N'PersonagemId', N'PersonagemHabilidadeHabilidadeId', N'PersonagemHabilidadePersonagemId') AND [object_id] = OBJECT_ID(N'[TB_PERSONAGENS_HABILIDADES]'))
    SET IDENTITY_INSERT [TB_PERSONAGENS_HABILIDADES] ON;
INSERT INTO [TB_PERSONAGENS_HABILIDADES] ([HabilidadeId], [PersonagemId], [PersonagemHabilidadeHabilidadeId], [PersonagemHabilidadePersonagemId])
VALUES (1, 1, NULL, NULL),
(2, 1, NULL, NULL),
(2, 2, NULL, NULL),
(2, 3, NULL, NULL),
(3, 3, NULL, NULL),
(3, 4, NULL, NULL),
(1, 5, NULL, NULL),
(2, 6, NULL, NULL),
(3, 7, NULL, NULL);
IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'HabilidadeId', N'PersonagemId', N'PersonagemHabilidadeHabilidadeId', N'PersonagemHabilidadePersonagemId') AND [object_id] = OBJECT_ID(N'[TB_PERSONAGENS_HABILIDADES]'))
    SET IDENTITY_INSERT [TB_PERSONAGENS_HABILIDADES] OFF;

CREATE INDEX [IX_TB_PERSONAGENS_HABILIDADES_HabilidadeId] ON [TB_PERSONAGENS_HABILIDADES] ([HabilidadeId]);

CREATE INDEX [IX_TB_PERSONAGENS_HABILIDADES_PersonagemHabilidadePersonagemId_PersonagemHabilidadeHabilidadeId] ON [TB_PERSONAGENS_HABILIDADES] ([PersonagemHabilidadePersonagemId], [PersonagemHabilidadeHabilidadeId]);

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20260505233913_MigracaoMuitosParaMuitos', N'10.0.5');

COMMIT;
GO

